import React from 'react';
import '../styles/cookiepolicy.css';

const CookiePolicy = () => {
  return (
    <div className="cookie-container">
      <div className="cookie-header">
        <h1>Cookie Policy</h1>
        <p>Last updated: May 17, 2025</p>
      </div>
      <div className="cookie-content">
      
      <h2>Our Commitment</h2>
      <p>Bharath Insight is committed to protecting your privacy and being transparent about the technologies we use on our website bharathinsight.com (“Website”). This Cookie Policy explains how and why we use cookies and the choices you have.</p>
      
      <h2>What are Cookies?</h2>
      <p>A cookie is a small text file that the Website saves on your device when you visit it. Cookies help the Website remember your actions and preferences, making your next visit easier and more personalized.</p>
      
      <h2>Why Do We Use Cookies?</h2>
      <p>We use cookies to:</p>
      <ul>
        <li>Provide you with our services and enhance your browsing experience</li>
        <li>Optimize and develop our Website</li>
        <li>Distinguish between human users and bots</li>
        <li>Perform analytics and research</li>
        <li>Detect and prevent fraud and unauthorized access</li>
      </ul>
      
      <h2>Types of Cookies We Use</h2>
      <p>We use both first-party and third-party cookies on our Website.</p>
      <ul>
        <li><strong>First-party Cookies:</strong> These are set by our Website and are essential for its operation.</li>
        <li><strong>Third-party Cookies:</strong> These are set by third parties, such as analytics providers, to help us understand how our Website is used.</li>
      </ul>
      
      <h2>Categories of Cookies We Use</h2>
      <ul>
        <li><strong>Strictly Necessary Cookies:</strong> Essential for the Website to function properly. They enable basic functions like page navigation and access to secure areas.</li>
        <li><strong>Performance Cookies:</strong> Collect data on how users interact with our Website to improve its performance.</li>
        <li><strong>Functional Cookies:</strong> Allow the Website to remember your choices and provide enhanced features.</li>
        <li><strong>Analytics Cookies:</strong> Help us understand how visitors use our Website by collecting anonymous data.</li>
      </ul>
      
      <h2>Managing Cookies</h2>
      <p>You can manage your cookie preferences through the cookie banner when you first visit our Website or by adjusting your browser settings. Please note that blocking certain cookies may affect the functionality of our Website.</p>
      
      <h2>Children's Privacy</h2>
      <p>Our Website is not intended for individuals under 18 years of age. We do not knowingly collect personal data from children. If we become aware that we have collected personal data from a child without parental consent, we will take steps to delete such data.</p>
      
      <h2>Contact Information</h2>
      <p>If you have any questions about this Cookie Policy, please contact us at bharathinsightnews@gmail.com.</p>
      
      <h2>Changes to This Cookie Policy</h2>
      <p>We may update this Policy from time to time. Any changes will be posted on this page with an updated revision date.</p>
      
      <h2>Advertising and Third-Party Cookies</h2>
      <p>We use third-party advertising services like Google AdSense on our Website. These services may use cookies and similar technologies to collect information about your browsing activities to deliver personalized advertisements that may be of interest to you. These advertising cookies do not store personal information directly but use a unique identifier in your browser or device.</p>
      
      <p>Third-party advertisers include:</p>
      <ul>
        <li><strong>Google AdSense</strong>: Uses cookies to serve ads based on your previous visits to our Website or other websites. Google's use of advertising cookies enables it and its partners to serve ads based on your interests and browsing patterns.</li>
        <li><strong>Google DoubleClick</strong>: Uses cookies to improve advertising, targeting ads that might be of more interest to you, limiting the number of times you see a specific ad, and measuring the effectiveness of ads.</li>
      </ul>
      
      <h2>Google Analytics</h2>
      <p>We use Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us analyze how users use our Website. The information generated by the cookie about your use of the Website will be transmitted to and stored by Google on servers in the United States.</p>
      <p>Google will use this information on our behalf for the purpose of evaluating your use of the Website, compiling reports on Website activity, and providing us with other services relating to Website activity and internet usage. You can prevent Google Analytics from using your data by downloading and installing the browser plugin available at: <a href="https://tools.google.com/dlpage/gaoptout" target="_blank">https://tools.google.com/dlpage/gaoptout</a>.</p>
      
      <h2>Opting Out of Cookies</h2>
      <p>Most web browsers allow you to manage your cookie preferences. You can set your browser to refuse cookies, or to alert you when cookies are being sent. The methods for doing so vary from browser to browser, and from version to version. You can obtain up-to-date information about blocking and deleting cookies via these links:</p>
      <ul>
        <li><a href="https://support.google.com/chrome/answer/95647" target="_blank">Google Chrome</a></li>
        <li><a href="https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop" target="_blank">Mozilla Firefox</a></li>
        <li><a href="https://support.microsoft.com/en-us/windows/microsoft-edge-browsing-data-and-privacy-bb8174ba-9d73-dcf2-9b4a-c582b4e640dd" target="_blank">Microsoft Edge</a></li>
        <li><a href="https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac" target="_blank">Apple Safari</a></li>
      </ul>
      <p>Please note that blocking all cookies may have a negative impact on the functionality of many websites, including our Website. Some cookies are essential for the Website to function properly, so disabling these might render some services unavailable.</p>
      
      <h2>Data Processing in the European Economic Area</h2>
      <p>If you are located in the European Economic Area (EEA), you have certain rights under the General Data Protection Regulation (GDPR) regarding the processing of your personal data. These rights include the right to access, correct, delete, restrict processing of, and object to our processing of your personal data.</p>
      <p>We only process personal data with your consent, to comply with our legal obligations, or when necessary for our legitimate interests or the legitimate interests of third parties, as described in this Cookie Policy. You have the right to withdraw your consent at any time.</p>
      
      <h2>International Transfers</h2>
      <p>Your personal information may be transferred to and processed in countries other than the country in which you are resident. These countries may have data protection laws that are different from those of your country. Specifically, our Website servers are located in the United States and India. In addition, our third-party service providers operate around the world.</p>
      <p>We have taken appropriate safeguards to ensure that your personal information will remain protected in accordance with this Cookie Policy when transferred internationally.</p>
      </div>
    </div>
  );
};

export default CookiePolicy;